title: Multi DOC
description: Modéle de documentation 
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Multi: https://multi.coop
aux_links_new_tab: true

mermaid:
  version: "10.0.8"

callouts:
  note:
    title: Note
    color: blue
